services:
  app:
    build: ./spring
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
    networks:
      - appmysql-net

  db:
    build: ./mysql
    ports:
      - "3306:3306"
    networks:
      appmysql-net:
        aliases:
          - mysql # Run on the network with this host name so that our Spring app can find it

networks:
  appmysql-net:
